# -*- coding: utf-8 -*-
"""DataAnalytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8TtLPSF_gCjLmfU5AU3zYDSkpmBgovm
"""

import pandas as pd
df = pd.read_csv('/content/healthcare_dataset.csv')
df

df.isnull().sum()

df.isnull()

df.describe()

df['Name']= df['Name'].str.upper()
df

